'use client'

import { useEffect, useMemo, useState } from 'react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Activity, BarChart3, ChevronDown, CircleHelp, CloudSun, Download, Gauge, LayoutDashboard, Menu, Settings2, Wind, X, Zap } from 'lucide-react'
import { exportPrediction, predictYield, type PredictionInputs } from '@/services/predictionService'

const initial: PredictionInputs = { ghi: 650, windSpeed: 8.2, temperature: 18, windDirection: 180, humidity: 58, lagPower: 4.1 }
const hours = ['00', '03', '06', '09', '12', '15', '18', '21']
const daily = [
  { day: 'Mon', solar: 18.4, wind: 11.2 }, { day: 'Tue', solar: 21.1, wind: 13.8 }, { day: 'Wed', solar: 19.7, wind: 12.5 }, { day: 'Thu', solar: 23.6, wind: 10.9 }, { day: 'Fri', solar: 22.2, wind: 15.1 }, { day: 'Sat', solar: 20.4, wind: 14.2 }, { day: 'Sun', solar: 24.1, wind: 12.8 },
]
const heatmap = Array.from({ length: 7 }, (_, day) => Array.from({ length: 12 }, (_, hour) => ({ day, hour, value: Math.round(18 + Math.max(0, Math.sin((hour - 2) / 10 * Math.PI)) * 62 + Math.sin(day * 1.8 + hour) * 8) }))).flat()
const tooltipStyle = { background: '#ffffff', border: '1px solid #dce4e8', borderRadius: 8, color: '#243746', fontSize: 12 }

function Sidebar({ open, onClose }: { open: boolean; onClose: () => void }) {
  const items = [['Overview', LayoutDashboard], ['Forecast', Activity], ['Analytics', BarChart3], ['Plant Health', Gauge], ['Data Import', Download]] as const
  return <aside className={`${open ? 'translate-x-0' : '-translate-x-full'} fixed inset-y-0 left-0 z-30 flex w-64 flex-col border-r border-slate-200 bg-[#243b53] text-white transition-transform lg:translate-x-0`}>
    <div className="flex h-20 items-center justify-between border-b border-white/10 px-6"><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#1d9a78] text-white"><Zap className="h-5 w-5" /></span><div><div className="text-lg font-bold tracking-tight">RENEW<span className="text-[#79c7ae]">GRID</span></div><div className="text-[9px] uppercase tracking-[.18em] text-slate-300">Energy authority</div></div></div><button className="lg:hidden" onClick={onClose} aria-label="Close navigation"><X className="h-5 w-5" /></button></div>
    <nav className="flex-1 space-y-1 px-3 py-6">{items.map(([label, Icon], index) => <button key={label} onClick={onClose} className={`flex w-full items-center gap-3 rounded-lg px-4 py-3 text-left text-sm transition ${index === 0 ? 'bg-white/12 font-semibold text-white' : 'text-slate-300 hover:bg-white/8 hover:text-white'}`}><Icon className="h-4 w-4" />{label}</button>)}<div className="my-6 border-t border-white/10" /><button className="flex w-full items-center gap-3 rounded-lg px-4 py-3 text-left text-sm text-slate-300 hover:bg-white/8 hover:text-white"><Settings2 className="h-4 w-4" />About System</button></nav>
    <div className="border-t border-white/10 p-5"><div className="mb-2 flex items-center gap-2 text-xs font-semibold"><span className="h-2 w-2 rounded-full bg-[#63c79f]" />System operational</div><p className="text-[11px] leading-5 text-slate-400">SOLETE co-located hybrid facility</p></div>
  </aside>
}

function KPI({ label, value, unit, icon: Icon, tone }: { label: string; value: string; unit: string; icon: typeof Zap; tone: string }) { return <div className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-medium text-slate-500">{label}</span><span className={`grid h-8 w-8 place-items-center rounded-md ${tone}`}><Icon className="h-4 w-4" /></span></div><div className="text-2xl font-bold tracking-tight text-[#243746]">{value}<span className="ml-1 text-sm font-medium text-slate-400">{unit}</span></div><div className="mt-2 text-[11px] text-[#1d9a78]">Live reading · updated now</div></div> }

export default function Home() {
  const [inputs, setInputs] = useState(initial)
  const [clock, setClock] = useState('')
  const [mobileNav, setMobileNav] = useState(false)
  const prediction = useMemo(() => predictYield(inputs), [inputs])
  const forecast = prediction.forecast.map((point, index) => ({ ...point, label: hours[index % hours.length] + ':00' }))
  const mix = [{ name: 'Solar', value: prediction.solar, color: '#e3b341' }, { name: 'Wind', value: prediction.wind * .62, color: '#2f8f72' }]
  useEffect(() => { const tick = () => setClock(new Date().toISOString().slice(0, 16).replace('T', ' · ') + ' UTC'); tick(); const id = setInterval(tick, 60000); return () => clearInterval(id) }, [])
  const download = (format: 'csv' | 'json') => { const blob = new Blob([exportPrediction(prediction, format)], { type: format === 'csv' ? 'text/csv' : 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `renewgrid-forecast.${format}`; a.click(); URL.revokeObjectURL(url) }
  return <div className="min-h-screen bg-[#f4f8f8] text-[#243746]"><Sidebar open={mobileNav} onClose={() => setMobileNav(false)} /><div className="lg:pl-64"><header className="flex h-20 items-center justify-between border-b border-slate-200 bg-white px-5 sm:px-8"><div className="flex items-center gap-3"><button className="lg:hidden" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu className="h-5 w-5" /></button><div><h1 className="text-lg font-bold tracking-tight sm:text-xl">Renewable Energy Overview</h1><p className="hidden text-xs text-slate-500 sm:block">Hybrid generation monitoring and yield forecasting</p></div></div><div className="flex items-center gap-3"><div className="hidden text-right sm:block"><div className="text-xs font-semibold text-slate-600">{clock}</div><div className="text-[10px] text-slate-400">Last data sync</div></div><span className="flex items-center gap-2 rounded-full bg-[#e8f5ef] px-3 py-2 text-xs font-semibold text-[#237b60]"><span className="h-2 w-2 rounded-full bg-[#2f8f72]" />Operational</span></div></header>
    <main className="mx-auto max-w-[1500px] p-5 sm:p-8"><div className="mb-6 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><div className="mb-1 text-xs font-semibold uppercase tracking-[.16em] text-[#1d9a78]">Portfolio / SOLETE facility</div><h2 className="text-2xl font-bold tracking-tight">Generation performance</h2></div><div className="flex items-center gap-2"><button className="rounded-md border border-slate-200 bg-white px-3 py-2 text-xs font-medium text-slate-600">Last 7 days <ChevronDown className="ml-2 inline h-3 w-3" /></button><button onClick={() => download('csv')} className="rounded-md bg-[#243b53] px-3 py-2 text-xs font-semibold text-white"><Download className="mr-2 inline h-3.5 w-3.5" />Export</button></div></div>
      <section className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KPI label="Current hybrid power" value={prediction.total.toFixed(1)} unit="kW" icon={Zap} tone="bg-[#e8f5ef] text-[#1d9a78]" /><KPI label="Current solar power" value={prediction.solar.toFixed(1)} unit="kW" icon={CloudSun} tone="bg-[#fff5d9] text-[#b88914]" /><KPI label="Current wind power" value={prediction.wind.toFixed(1)} unit="kW" icon={Wind} tone="bg-[#e7f0f6] text-[#39708b]" /><KPI label="Today’s energy yield" value={(prediction.total * 8.6).toFixed(0)} unit="kWh" icon={Gauge} tone="bg-[#eef0fb] text-[#5967a5]" /></section>
      <section className="mb-6 rounded-lg border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="mb-5 flex items-start justify-between"><div><h3 className="font-semibold">Hybrid generation forecast</h3><p className="mt-1 text-xs text-slate-500">Observed and predicted power output · kW</p></div><div className="flex gap-4 text-xs text-slate-500"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#243b53]" />Hybrid</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#e3b341]" />Solar</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#2f8f72]" />Wind</span></div></div><ResponsiveContainer width="100%" height={330}><LineChart data={forecast} margin={{ top: 8, right: 12, left: -20, bottom: 0 }}><CartesianGrid stroke="#edf1f2" vertical={false} /><XAxis dataKey="label" tick={{ fill: '#84929b', fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: '#84929b', fontSize: 11 }} axisLine={false} tickLine={false} unit=" kW" /><Tooltip contentStyle={tooltipStyle} /><Line type="monotone" dataKey="total" stroke="#243b53" strokeWidth={3} dot={false} name="Hybrid" /><Line type="monotone" dataKey="solar" stroke="#e3b341" strokeWidth={2} dot={false} name="Solar" /><Line type="monotone" dataKey="wind" stroke="#2f8f72" strokeWidth={2} dot={false} name="Wind" /></LineChart></ResponsiveContainer></section>
      <section className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><div className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="mb-5"><h3 className="font-semibold">Energy yield by day</h3><p className="mt-1 text-xs text-slate-500">Daily contribution by generation source · MWh</p></div><ResponsiveContainer width="100%" height={250}><BarChart data={daily} margin={{ left: -20, right: 8 }}><CartesianGrid stroke="#edf1f2" vertical={false} /><XAxis dataKey="day" tick={{ fill: '#84929b', fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: '#84929b', fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="solar" stackId="energy" fill="#e3b341" name="Solar" radius={[3, 3, 0, 0]} /><Bar dataKey="wind" stackId="energy" fill="#2f8f72" name="Wind" /></BarChart></ResponsiveContainer></div><div className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="mb-2"><h3 className="font-semibold">Current energy mix</h3><p className="mt-1 text-xs text-slate-500">Source contribution to hybrid output</p></div><div className="relative"><ResponsiveContainer width="100%" height={200}><PieChart><Pie data={mix} dataKey="value" nameKey="name" innerRadius={57} outerRadius={78} paddingAngle={3}><Cell fill="#e3b341" /><Cell fill="#2f8f72" /></Pie><Tooltip contentStyle={tooltipStyle} /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><div><div className="text-2xl font-bold">{prediction.total.toFixed(1)}</div><div className="text-[10px] text-slate-400">kW total</div></div></div></div><div className="space-y-3">{mix.map((item) => <div key={item.name} className="flex items-center justify-between text-xs"><span className="text-slate-600"><i className="mr-2 inline-block h-2.5 w-2.5 rounded-full" style={{ background: item.color }} />{item.name}</span><span className="font-semibold">{Math.round(item.value / (mix[0].value + mix[1].value) * 100)}%</span></div>)}</div></div></section>
      <section className="mt-6 rounded-lg border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="mb-5"><h3 className="font-semibold">Generation intensity by hour</h3><p className="mt-1 text-xs text-slate-500">Relative output across the monitored week</p></div><div className="overflow-x-auto"><div className="min-w-[620px]"><div className="mb-2 ml-12 grid grid-cols-12 gap-1 text-[10px] text-slate-400">{Array.from({ length: 12 }, (_, index) => <span key={index}>{String(index * 2).padStart(2, '0')}</span>)}</div>{Array.from({ length: 7 }, (_, day) => <div key={day} className="mb-1 flex items-center gap-2"><span className="w-10 text-right text-[10px] text-slate-400">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][day]}</span><div className="grid flex-1 grid-cols-12 gap-1">{heatmap.filter((cell) => cell.day === day).map((cell) => <div key={`${cell.day}-${cell.hour}`} title={`${cell.value}% intensity`} className="h-6 rounded-sm" style={{ background: `rgba(47, 143, 114, ${0.08 + cell.value / 130})` }} />)}</div></div>)}</div></div></section>
      <footer className="flex flex-col justify-between gap-3 border-t border-slate-200 py-6 text-xs text-slate-500 sm:flex-row"><span>RenewGrid monitoring platform · SOLETE co-located facility</span><span className="flex items-center gap-2"><CircleHelp className="h-3.5 w-3.5" />Data refreshed from connected processing service</span></footer>
    </main></div></div>
}
