'use client'

import { useEffect, useMemo, useState } from 'react'
import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Activity, ArrowUpRight, BarChart3, Check, ChevronDown, CloudSun, Download, Gauge, GaugeCircle, Wind, Zap } from 'lucide-react'
import { exportPrediction, predictYield, presets, type PredictionInputs } from '@/services/predictionService'

const initial: PredictionInputs = { ghi: 450, windSpeed: 7.5, temperature: 18, windDirection: 180, humidity: 65, lagPower: 4.1 }
const controls: { key: keyof PredictionInputs; label: string; min: number; max: number; step: number; unit: string }[] = [
  { key: 'ghi', label: 'Solar irradiance', min: 0, max: 1000, step: 10, unit: 'W/m²' },
  { key: 'windSpeed', label: 'Wind speed', min: 0, max: 25, step: 0.1, unit: 'm/s' },
  { key: 'temperature', label: 'Ambient temperature', min: -10, max: 45, step: 1, unit: '°C' },
  { key: 'windDirection', label: 'Wind direction', min: 0, max: 360, step: 1, unit: '°' },
  { key: 'humidity', label: 'Relative humidity', min: 0, max: 100, step: 1, unit: '%' },
  { key: 'lagPower', label: 'Recent power lag', min: 0, max: 11, step: 0.1, unit: 'kW' },
]
const models = [['Hybrid Voting Ensemble', '0.9227', '0.235', '0.473', '0.9607'], ['LightGBM Regressor', '0.9224', '0.238', '0.473', '0.9606'], ['XGBoost Regressor', '0.9214', '0.240', '0.477', '0.9600'], ['Random Forest', '0.9194', '0.239', '0.482', '0.9590'], ['Gradient Boosting', '0.9187', '0.246', '0.485', '0.9585'], ['Ridge Regression', '0.9035', '0.295', '0.528', '0.9525']]
const features = [['Recent hybrid power lag', 80.4], ['Hybrid ramp rate delta', 2.4], ['Hour of day', 2.4], ['Sun trajectory · sin_hour', 2.3], ['Solar ramp delta', 1.6], ['Plane of array irradiance', 1.6], ['Global horizontal irradiance', 1.5], ['Wind speed & aerodynamic vectors', 1.4]]

function SectionLabel({ children, eyebrow }: { children: React.ReactNode; eyebrow: string }) { return <div className="mb-5"><div className="mb-2 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.22em] text-hybrid"><span className="h-px w-6 bg-hybrid" />{eyebrow}</div><h2 className="text-xl font-semibold tracking-tight text-foreground">{children}</h2></div> }
function Metric({ label, value, tone }: { label: string; value: string; tone: 'solar'|'wind'|'hybrid' }) { return <div className="rounded-xl border border-border/80 bg-black/10 p-4"><div className={`mb-3 flex items-center gap-2 text-xs text-${tone}`}><span className={`h-1.5 w-1.5 rounded-full bg-${tone}`} />{label}</div><div className="font-mono text-2xl font-semibold text-foreground">{value}</div></div> }

export default function Home() {
  const [inputs, setInputs] = useState(initial)
  const [clock, setClock] = useState('')
  const [visible, setVisible] = useState({ solar: true, wind: true, total: true })
  const prediction = useMemo(() => predictYield(inputs), [inputs])
  useEffect(() => { const tick = () => setClock(new Date().toISOString().slice(11, 19) + ' UTC'); tick(); const id = setInterval(tick, 1000); return () => clearInterval(id) }, [])
  const setValue = (key: keyof PredictionInputs, value: number) => setInputs((current) => ({ ...current, [key]: value }))
  const download = (format: 'csv'|'json') => { const blob = new Blob([exportPrediction(prediction, format)], { type: format === 'csv' ? 'text/csv' : 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `hybrid-dispatch.${format}`; a.click(); URL.revokeObjectURL(url) }
  return <main className="grid-bg min-h-screen overflow-hidden">
    <div className="mx-auto max-w-[1440px] px-5 py-6 sm:px-8 lg:px-12">
      <header className="mb-10 flex flex-col justify-between gap-6 border-b border-border/80 pb-7 lg:flex-row lg:items-end">
        <div><div className="mb-4 flex items-center gap-3 text-xs font-semibold uppercase tracking-[.2em] text-hybrid"><span className="pulse-dot h-2 w-2 rounded-full bg-hybrid" />Energy intelligence platform</div><h1 className="max-w-3xl text-3xl font-semibold tracking-[-.04em] text-foreground sm:text-5xl">Hybrid Solar-Wind<br /><span className="text-hybrid">Energy Yield Predictor</span></h1><p className="mt-4 max-w-2xl text-sm leading-6 text-muted">Co-located renewable energy yield forecasting & dispatch optimization engine.</p></div>
        <div className="flex flex-wrap gap-2 text-[11px] text-muted"><span className="rounded-full border border-hybrid/30 bg-hybrid/10 px-3 py-2 text-hybrid">Model active</span><span className="rounded-full border border-border px-3 py-2">DTU SOLETE · 15 months</span><span className="rounded-full border border-border px-3 py-2">R² 0.9227</span><span className="rounded-full border border-border px-3 py-2 font-mono">{clock || '00:00:00 UTC'}</span></div>
      </header>

      <section className="mb-12 grid gap-5 lg:grid-cols-[1.05fr_.95fr]">
        <div className="glass rounded-2xl p-5 sm:p-7"><div className="mb-7 flex items-start justify-between"><SectionLabel eyebrow="Live prediction">Tune the weather signal</SectionLabel><div className="flex items-center gap-2 text-xs text-wind"><span className="pulse-dot h-2 w-2 rounded-full bg-wind" />Operational</div></div><div className="grid gap-x-8 gap-y-5 sm:grid-cols-2">{controls.map((control) => <label key={control.key} className="block"><div className="mb-2 flex justify-between text-xs text-muted"><span>{control.label}</span><span className="font-mono text-foreground">{inputs[control.key]} {control.unit}</span></div><input aria-label={control.label} type="range" min={control.min} max={control.max} step={control.step} value={inputs[control.key]} onChange={(e) => setValue(control.key, Number(e.target.value))} className="w-full" />{control.key === 'windDirection' && <div className="mt-2 flex items-center gap-2 text-[10px] text-muted"><span className="inline-flex h-6 w-6 items-center justify-center rounded-full border border-border" style={{ transform: `rotate(${inputs.windDirection}deg)` }}>↑</span>Heading vector</div>}</label>)}</div><div className="mt-8 flex flex-wrap gap-2 border-t border-border/70 pt-5"><span className="mr-2 py-2 text-xs text-muted">Quick presets</span>{Object.keys(presets).map((name) => <button key={name} onClick={() => setInputs(presets[name])} className="rounded-lg border border-border bg-white/[.03] px-3 py-2 text-xs text-muted transition hover:border-hybrid hover:text-foreground">{name}</button>)}</div></div>
        <div className="glass relative overflow-hidden rounded-2xl p-5 sm:p-7"><div className="absolute -right-16 -top-16 h-48 w-48 rounded-full bg-hybrid/10 blur-3xl" /><div className="relative flex h-full flex-col justify-between"><div><SectionLabel eyebrow="Current system output">Predicted hybrid yield</SectionLabel><div className="flex items-center gap-6"><div className="relative grid h-36 w-36 place-items-center rounded-full" style={{ background: `conic-gradient(#06b6d4 ${Math.min(prediction.capacityFactor, 100)}%, #1b2a3f 0)` }}><div className="grid h-28 w-28 place-items-center rounded-full bg-[#101827]"><div className="text-center"><div className="font-mono text-3xl font-semibold text-foreground">{prediction.total.toFixed(2)}</div><div className="text-[10px] uppercase tracking-wider text-muted">kW total</div></div></div></div><div><div className="mb-2 flex items-center gap-2 text-xs text-muted"><GaugeCircle className="h-4 w-4 text-hybrid" />Capacity factor</div><div className="font-mono text-3xl text-hybrid">{prediction.capacityFactor}%</div><div className="mt-1 text-xs text-muted">of 11.0 kW rated capacity</div></div></div></div><div className="mt-8 grid grid-cols-2 gap-3"><Metric label="Solar PV contribution" value={`${prediction.solar.toFixed(2)} kW`} tone="solar" /><Metric label="Wind turbine contribution" value={`${prediction.wind.toFixed(2)} kW`} tone="wind" /><div className="col-span-2 flex items-center justify-between rounded-xl border border-border/80 bg-black/10 p-4 text-xs"><span className="text-muted">Solar / wind ratio</span><span className="font-mono text-foreground">{prediction.ratio}% <span className="text-muted">/ {100 - prediction.ratio}%</span></span></div></div></div></div>
      </section>

      <section className="mb-12"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><SectionLabel eyebrow="Forecast horizon">24-hour dispatch forecast</SectionLabel><div className="flex gap-2">{(['solar','wind','total'] as const).map((key) => <button key={key} onClick={() => setVisible((v) => ({ ...v, [key]: !v[key] }))} className={`flex items-center gap-2 rounded-lg border px-3 py-2 text-xs capitalize ${visible[key] ? `border-${key === 'solar' ? 'solar' : key === 'wind' ? 'wind' : 'hybrid'}/50 bg-white/[.04] text-foreground` : 'border-border text-muted opacity-60'}`}><span className={`h-2 w-2 rounded-full bg-${key === 'solar' ? 'solar' : key === 'wind' ? 'wind' : 'hybrid'}`} />{key}</button>)}</div></div><div className="glass rounded-2xl p-4 sm:p-6"><ResponsiveContainer width="100%" height={300}><AreaChart data={prediction.forecast} margin={{ top: 10, right: 5, left: -20, bottom: 0 }}><defs><linearGradient id="hybridFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#06b6d4" stopOpacity={.32}/><stop offset="100%" stopColor="#06b6d4" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="hour" interval={2}/><YAxis unit=" kW"/><Tooltip contentStyle={{ background: '#101827', border: '1px solid #2b3b52', borderRadius: 10, fontSize: 12 }} /><Area hide={!visible.total} type="monotone" dataKey="total" stroke="#06b6d4" fill="url(#hybridFill)" strokeWidth={2} name="Hybrid"/><Line hide={!visible.solar} type="monotone" dataKey="solar" stroke="#f59e0b" strokeWidth={2} dot={false} name="Solar"/><Line hide={!visible.wind} type="monotone" dataKey="wind" stroke="#10b981" strokeWidth={2} dot={false} name="Wind"/></AreaChart></ResponsiveContainer></div></section>

      <section className="mb-12 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div><SectionLabel eyebrow="Model performance">Benchmark leaderboard</SectionLabel><div className="glass overflow-x-auto rounded-2xl"><table className="w-full min-w-[650px] text-left text-xs"><thead className="border-b border-border text-[10px] uppercase tracking-wider text-muted"><tr><th className="px-5 py-4">Model</th><th>R²</th><th>MAE</th><th>RMSE</th><th>Pearson r</th></tr></thead><tbody>{models.map((model, index) => <tr key={model[0]} className={`border-b border-border/60 last:border-0 ${index === 0 ? 'bg-hybrid/[.06]' : ''}`}><td className="px-5 py-4 font-medium text-foreground">{index === 0 && <span className="mr-2 rounded bg-hybrid/15 px-2 py-1 text-[9px] text-hybrid">WINNER</span>}{model[0]}</td>{model.slice(1).map((value) => <td key={value} className="font-mono text-muted">{value}</td>)}</tr>)}</tbody></table></div><div className="mt-3 flex items-center gap-2 text-xs text-muted"><Check className="h-4 w-4 text-hybrid" />Ensemble wins through error cancellation between bagging and boosting.</div></div><div><SectionLabel eyebrow="Explainability">Feature importance</SectionLabel><div className="glass rounded-2xl p-5">{features.map(([label, value]) => <div key={label as string} className="mb-4 last:mb-0"><div className="mb-1 flex justify-between gap-3 text-[11px] text-muted"><span>{label}</span><span className="font-mono text-foreground">{value}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-border"><div className="h-full rounded-full bg-hybrid" style={{ width: `${Math.max(Number(value), 1.5) / 80.4 * 100}%`, opacity: Number(value) > 10 ? 1 : .7 }} /></div></div>)}</div></div></section>

      <footer className="border-t border-border/80 py-8"><div className="flex flex-col justify-between gap-6 lg:flex-row"><div><div className="mb-3 flex items-center gap-2 text-sm font-semibold"><Zap className="h-4 w-4 text-hybrid" />The SOLETE test facility</div><p className="max-w-xl text-xs leading-6 text-muted">DTU&apos;s physical research station in Denmark pairs a Gaia 11kW wind turbine, co-located PV array, and weather station on the same substation for continuous hybrid telemetry.</p></div><div className="flex flex-wrap items-start gap-2 text-[11px] text-muted"><span className="rounded border border-border px-3 py-2">Python 3.12</span><span className="rounded border border-border px-3 py-2">Scikit-Learn</span><span className="rounded border border-border px-3 py-2">XGBoost</span><span className="rounded border border-border px-3 py-2">LightGBM</span><button onClick={() => download('csv')} className="flex items-center gap-2 rounded border border-hybrid/40 bg-hybrid/10 px-3 py-2 text-hybrid transition hover:bg-hybrid/20"><Download className="h-3.5 w-3.5" />Export CSV</button><button onClick={() => download('json')} className="rounded border border-border px-3 py-2 transition hover:border-hybrid hover:text-foreground">JSON</button></div></div></footer>
    </div>
  </main>
}
